version: "2.2"

services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - "39000:9000"
      - "39092:9092"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - db
    restart: unless-stopped
    cpuset: 0,1
    mem_limit: 1G
    memswap_limit: -1
    mem_reservation: 64M

  db:
    image: postgres:10.0
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - ./db:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./db/data:/var/lib/postgresql/data
    restart: unless-stopped
    cpuset: 0,1
    mem_limit: 1G
    memswap_limit: -1
    mem_reservation: 256M

networks:
  sonarnet:
    driver: bridge
